insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (1, 'm', '1983-06-13', 1, 'Applic ext fix dev-femur', 'Gedangan', 'Indonesia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (2, 'm', '1985-01-04', 2, 'Injection into marrow', 'Sabang', 'Philippines');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (3, 'm', '1997-12-27', 3, 'Salivary cyst marsupial', 'Gostimë', 'Albania');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (4, 'f', '2003-01-13', 4, 'Implt/repl carddefib tot', 'Shikārpur', 'Pakistan');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (5, 'f', '1994-12-15', 5, 'Humerus sequestrectomy', 'Anastácio', 'Brazil');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (6, 'm', '2002-05-18', 6, 'Revision of pedicle grft', 'Pingdong', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (7, 'm', '1982-02-27', 7, 'Lid reconstr w graft NEC', 'Muurame', 'Finland');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (8, 'f', '1997-05-15', 8, 'Papillary muscle ops', 'Ban Phaeo', 'Thailand');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (9, 'm', '1996-08-05', 9, 'Rev knee replace-patella', 'Thạnh Mỹ', 'Vietnam');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (10, 'f', '1982-04-23', 10, 'Destr sm bowel les NEC', 'Pingshui', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (11, 'f', '1989-08-23', 11, 'Artif rupt membranes NEC', 'Charlotte Amalie', 'U.S. Virgin Islands');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (12, 'x', '2003-03-11', 12, 'Endo transmyo revascular', 'Bergen', 'Norway');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (13, 'f', '2001-07-03', 13, 'Destruct abd wall lesion', 'Starý Bohumín', 'Czech Republic');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (14, 'm', '1988-06-16', 14, 'Adm neuroprotective agnt', 'Muruni', 'Indonesia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (15, 'f', '1993-09-06', 15, 'Metatarsal/tarsal biopsy', 'Yerba Buena', 'Argentina');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (16, 'f', '2003-12-25', 16, 'Total body perfusion', 'Cruzeiro', 'Portugal');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (17, 'f', '1994-03-30', 17, 'Joint biopsy NEC', 'Seynod', 'France');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (18, 'f', '1982-10-04', 18, 'Cystotomy & adhesiolysis', 'Matai', 'Tanzania');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (19, 'f', '1994-08-01', 19, 'Excis metacar/car-graft', 'Pedro Sánchez', 'Dominican Republic');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (20, 'f', '1985-05-10', 20, 'Close thoracic duct fist', 'Huanggong', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (21, 'm', '2000-08-18', 21, 'Access-hypogloss anastom', 'Tongqing', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (22, 'm', '1986-02-23', 22, 'Total repair of tapvc', 'Lhakangtang', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (23, 'f', '1994-09-16', 23, 'Duhamel rectal resection', 'Noailles', 'France');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (24, 'm', '2001-03-26', 24, 'Peripheral nerve suture', 'Gulbene', 'Latvia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (25, 'f', '1980-11-13', 25, 'Other nasal sinus ops', 'Elliot', 'South Africa');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (26, 'x', '1988-04-22', 26, 'Infus immunosup antibody', 'Yukuriawat', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (27, 'm', '1999-08-18', 27, 'Correct everted punctum', 'Wien', 'Austria');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (28, 'f', '1997-06-07', 28, 'Mesenteric repair NEC', 'Novovarshavka', 'Russia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (29, 'f', '1982-04-07', 29, 'Replace ventricle shunt', 'Penitik', 'Indonesia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (30, 'm', '1997-09-26', 30, 'Respiratory measure NEC', 'Santos', 'Brazil');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (31, 'm', '1983-04-14', 31, 'Bil breast injec-augment', 'Degerfors', 'Sweden');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (32, 'f', '1991-04-21', 32, 'Audiometry', 'Pirajuí', 'Brazil');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (33, 'm', '2002-08-29', 33, 'Culture-op wound', 'Ballisodare', 'Ireland');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (34, 'f', '1998-12-15', 34, 'Uterine repair NEC', 'Sabaneta', 'Venezuela');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (35, 'f', '2001-06-19', 35, 'Parasitology-peritoneum', 'Taikang', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (36, 'm', '1993-01-16', 36, 'Peritoneal biopsy', 'Leixlip', 'Ireland');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (37, 'f', '1994-11-02', 37, 'Remov intralum colon FB', 'Papineauville', 'Canada');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (38, 'f', '1985-11-24', 38, 'Remove head/neck dev NEC', 'Bandera', 'Argentina');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (39, 'm', '1988-11-04', 39, 'Abdperneal resc rect NEC', 'Yanbei', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (40, 'm', '1981-07-23', 40, 'Esophag stricture repair', 'Yashiro', 'Japan');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (41, 'x', '1996-05-12', 41, 'Intracran endarterectomy', 'Massy', 'France');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (42, 'f', '1983-04-16', 42, 'Psychol mental stat NOS', 'Latacunga', 'Ecuador');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (43, 'm', '1981-12-23', 43, 'Miscellaneous proc NEC', 'Kuhmalahti', 'Finland');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (44, 'f', '1983-06-28', 44, 'Psychiat mental determin', 'Siay', 'Philippines');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (45, 'f', '1997-09-10', 45, 'Arterial catheterization', 'Üydzen', 'Mongolia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (46, 'm', '1981-11-23', 46, 'Conjunc free graft NEC', 'Palopat', 'Indonesia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (47, 'm', '1990-12-08', 47, 'Suture of palate lacerat', 'Palaiomonástiron', 'Greece');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (48, 'f', '1995-05-18', 48, 'Pelvic gas contrast xray', 'Caen', 'France');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (49, 'f', '1995-01-04', 49, 'Repair vag fistula NEC', 'Matadi', 'Democratic Republic of the Congo');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (50, 'f', '1990-05-15', 50, 'Atrial cardioversion', 'Gangbei', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (51, 'x', '1990-07-26', 51, 'Other chest wall repair', 'Huolongmen', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (52, 'x', '1998-03-11', 52, 'Eye enuc w implant NEC', 'Pruchnik', 'Poland');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (53, 'm', '1983-10-15', 53, 'Revis bile tract anastom', 'Louisville', 'United States');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (54, 'm', '1986-04-15', 54, 'Excise lg intestine les', 'Tojeira', 'Portugal');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (55, 'f', '1981-06-30', 55, 'PlEuroperitoneal shunt', 'Wujiabao', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (56, 'm', '1981-05-26', 56, 'Remov intralum gastr FB', 'Załuski', 'Poland');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (57, 'f', '1996-12-08', 57, 'External ear biopsy', 'Glushkovo', 'Russia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (58, 'f', '1982-04-10', 58, 'Forearm/wrist/hand reatt', 'Jamao al Norte', 'Dominican Republic');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (59, 'f', '1985-08-02', 59, 'Elbow arthroplasty NEC', 'Bagacay', 'Philippines');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (60, 'm', '1989-02-24', 60, 'Subtalar fusion', 'Conchopata', 'Peru');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (61, 'f', '2001-01-30', 61, 'Skull & brain op NEC', 'Zhlobin', 'Belarus');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (62, 'x', '2002-08-06', 62, 'Tympanosympathectomy', 'Kameyama', 'Japan');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (63, 'm', '1989-11-20', 63, 'Spine meningocele repair', 'Urengoy', 'Russia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (64, 'm', '1996-06-17', 64, 'Tooth restorat by inlay', 'Wufeng', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (65, 'm', '1984-09-23', 65, 'Open large bowel biopsy', 'Santo Amaro', 'Portugal');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (66, 'm', '1988-11-24', 66, 'Applic ext fix-humerus', 'Memória', 'Portugal');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (67, 'm', '1986-12-27', 67, 'Clinical hearing test', 'Santa Rosa', 'Uruguay');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (68, 'f', '1986-05-31', 68, 'Part gastrec w jej anast', 'Taklale', 'Indonesia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (69, 'm', '1986-06-04', 69, 'Simpl aspir lens extract', 'Gorodishche', 'Russia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (70, 'm', '1998-08-28', 70, 'Imp/rep subcue card dev', 'Khemisset', 'Morocco');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (71, 'f', '1981-11-01', 71, 'Hip surface, cermc/poly', 'Gaogu', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (72, 'm', '1994-04-16', 72, 'Open robotic assist proc', 'Tha Bo', 'Thailand');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (73, 'm', '1984-12-15', 73, 'Uroflowmetry', 'María la Baja', 'Colombia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (74, 'm', '2000-09-26', 74, 'Removal iud', 'Tagum', 'Philippines');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (75, 'm', '1994-09-15', 75, 'Toxicology-lymph system', 'Berekum', 'Ghana');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (76, 'f', '1992-08-03', 76, 'Lumb/lmbosac fus ant/ant', 'Lizhai', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (77, 'm', '1991-08-28', 77, 'Lmb/lmbsac fus post/post', 'Charikar', 'Afghanistan');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (78, 'f', '1998-02-09', 78, 'Fallopian tube biopsy', 'Kyonju', 'South Korea');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (79, 'x', '1999-10-14', 79, 'Radius & ulna sequestrec', 'Mariestad', 'Sweden');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (80, 'f', '1984-09-07', 80, 'Aortocoronary bypass NOS', 'Paôy Pêt', 'Cambodia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (81, 'f', '1986-04-13', 81, 'Arterial catheterization', 'Vetluzhskiy', 'Russia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (82, 'x', '2001-01-25', 82, 'Lap remove both ovaries', 'Ban Takhun', 'Thailand');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (83, 'm', '1998-10-11', 83, 'Oth totl excision thymus', 'Nggelok', 'Indonesia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (84, 'f', '1991-05-22', 84, 'Latiss dorsi myocut flap', 'Puncakwangi', 'Indonesia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (85, 'f', '1984-05-21', 85, 'Occlude arm vessel NEC', 'Los Pinos', 'Mexico');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (86, 'f', '1993-04-05', 86, 'Keratoprosthesis', 'Glória do Goitá', 'Brazil');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (87, 'f', '1999-01-15', 87, 'Oth perc proc bil trct', 'Roma', 'Italy');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (88, 'f', '1994-12-03', 88, 'Pancreatic anastomosis', 'San Fernando', 'Honduras');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (89, 'm', '1984-12-23', 89, 'Repair retina detach NEC', 'Wonokerto', 'Indonesia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (90, 'f', '1986-10-15', 90, 'Delayed tendon suture', 'Ntsoudjini', 'Comoros');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (91, 'f', '2002-08-25', 91, 'Laparoscopic cecectomy', 'Lampuyang', 'Indonesia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (92, 'f', '1999-09-25', 92, 'Tooth restor by filling', 'Hairag', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (93, 'f', '1985-10-19', 93, 'Intravenous pyelogram', 'Ayapa', 'Honduras');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (94, 'x', '1984-05-30', 94, 'Dilation of intestine', 'Gurgurnica', 'Macedonia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (95, 'f', '1990-01-11', 95, 'Autoimmune dis immunizat', 'Phan Thong', 'Thailand');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (96, 'f', '1986-10-31', 96, 'Ocular prosthetics', 'Kloangpopot', 'Indonesia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (97, 'm', '1998-11-08', 97, 'Multisource radiosurgery', 'Chongxing', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (98, 'f', '1996-09-12', 98, 'Male sterilization NOS', 'Sabi', 'Gambia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (99, 'm', '1994-06-09', 99, 'Urin incontin repair NEC', 'El Soberbio', 'Argentina');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (100, 'f', '1988-08-19', 100, 'IV infusion clofarabine', 'El Almendro', 'Nicaragua');
