insert into communities (id, name, description, admin_id) values (1, 'Domainer', 'Open wound of nose NOS', 70);
insert into communities (id, name, description, admin_id) values (2, 'Gembucket', 'Optic nerve injury', 67);
insert into communities (id, name, description, admin_id) values (3, 'Solarbreeze', 'Injury-firearm/expl NOS', 45);
insert into communities (id, name, description, admin_id) values (4, 'Alpha', 'Concus-brf coma 31-59 mn', 2);
insert into communities (id, name, description, admin_id) values (5, 'Flowdesk', 'Prim TB pleuris-histo dx', 100);
insert into communities (id, name, description, admin_id) values (6, 'Cardguard', 'Assault-gasoline bomb', 30);
insert into communities (id, name, description, admin_id) values (7, 'Veribet', 'Extreme immat 1000-1249g', 78);
insert into communities (id, name, description, admin_id) values (8, 'Solarbreeze', 'TB laryngitis-oth test', 75);
insert into communities (id, name, description, admin_id) values (9, 'Stronghold', 'Burn NOS arm-multiple', 71);
insert into communities (id, name, description, admin_id) values (10, 'Overhold', 'Jt contracture-ankle', 10);
insert into communities (id, name, description, admin_id) values (11, 'Opela', 'Unil femoral hern w gang', 88);
insert into communities (id, name, description, admin_id) values (12, 'Overhold', 'Brain lacer NEC w/o coma', 23);
insert into communities (id, name, description, admin_id) values (13, 'Cardify', 'Oth myl leuk w rmsion', 14);
insert into communities (id, name, description, admin_id) values (14, 'Sub-Ex', 'Monocular esotropia', 63);
insert into communities (id, name, description, admin_id) values (15, 'Prodder', 'Vasc comp mesenteric art', 6);
insert into communities (id, name, description, admin_id) values (16, 'Konklab', 'Dissociative fugue', 21);
insert into communities (id, name, description, admin_id) values (17, 'Cardguard', 'Brain injury NEC', 32);
insert into communities (id, name, description, admin_id) values (18, 'Biodex', 'Generalized anxiety dis', 60);
insert into communities (id, name, description, admin_id) values (19, 'Treeflex', 'Mat anesth/analg aff NB', 26);
insert into communities (id, name, description, admin_id) values (20, 'Otcom', 'Quads w fetal loss-ante', 11);
insert into communities (id, name, description, admin_id) values (21, 'Redhold', 'Drug dependence-deliver', 59);
insert into communities (id, name, description, admin_id) values (22, 'Aerified', 'Malig neo biliary NOS', 5);
insert into communities (id, name, description, admin_id) values (23, 'Tin', 'Colles'' fracture-open', 9);
insert into communities (id, name, description, admin_id) values (24, 'Bamity', 'Sec neuroendo tumor-bone', 35);
insert into communities (id, name, description, admin_id) values (25, 'Home Ing', 'Pericardial disease NOS', 90);
insert into communities (id, name, description, admin_id) values (26, 'Matsoft', '50-59% bdy brn/3 deg NOS', 29);
insert into communities (id, name, description, admin_id) values (27, 'Lotstring', 'Schizophreniform dis NOS', 62);
insert into communities (id, name, description, admin_id) values (28, 'Sub-Ex', 'Radial styloid tenosynov', 10);
insert into communities (id, name, description, admin_id) values (29, 'Flowdesk', 'Meningitis oth spcf bact', 42);
insert into communities (id, name, description, admin_id) values (30, 'Temp', 'Senile cataract NEC', 73);
insert into communities (id, name, description, admin_id) values (31, 'Konklab', 'Lethal midline granuloma', 15);
insert into communities (id, name, description, admin_id) values (32, 'Andalax', 'Pure hypercholesterolem', 69);
insert into communities (id, name, description, admin_id) values (33, 'Bitchip', 'Screen for gu cond NEC', 79);
insert into communities (id, name, description, admin_id) values (34, 'Lotlux', 'Perinat jaund-hered anem', 10);
insert into communities (id, name, description, admin_id) values (35, 'Zaam-Dox', 'Glaucoma NOS', 50);
insert into communities (id, name, description, admin_id) values (36, 'Bitwolf', 'Astigmatism NOS', 33);
insert into communities (id, name, description, admin_id) values (37, 'Trippledex', 'Mal neo thorax/resp NEC', 71);
insert into communities (id, name, description, admin_id) values (38, 'Treeflex', 'Adv eff antibiotics NEC', 38);
insert into communities (id, name, description, admin_id) values (39, 'Voltsillam', 'Fx up ulna NEC/NOS-open', 10);
insert into communities (id, name, description, admin_id) values (40, 'Tres-Zap', 'Priv dwel fire-accid NOS', 81);
insert into communities (id, name, description, admin_id) values (41, 'Andalax', 'Drop, hematocrit, precip', 14);
insert into communities (id, name, description, admin_id) values (42, 'Cardguard', 'Complx febrile convulsns', 18);
insert into communities (id, name, description, admin_id) values (43, 'Toughjoyfax', 'E.coli infection NEC/NOS', 60);
insert into communities (id, name, description, admin_id) values (44, 'Namfix', 'Acute miliary tb-unspec', 65);
insert into communities (id, name, description, admin_id) values (45, 'Transcof', 'Prelabor rupt uterus-del', 50);
insert into communities (id, name, description, admin_id) values (46, 'Redhold', 'Path fx dstl radius ulna', 17);
insert into communities (id, name, description, admin_id) values (47, 'Zoolab', 'Assault-hunting rifle', 49);
insert into communities (id, name, description, admin_id) values (48, 'Hatity', 'Acquired night blindness', 27);
insert into communities (id, name, description, admin_id) values (49, 'Zathin', 'Retain nonmag meta frag', 29);
insert into communities (id, name, description, admin_id) values (50, 'Y-find', 'Ac bulbar polio-type 2', 31);
insert into communities (id, name, description, admin_id) values (51, 'Zaam-Dox', 'Rosacea conjunctivitis', 100);
insert into communities (id, name, description, admin_id) values (52, 'Hatity', 'Joint effusion-up/arm', 30);
insert into communities (id, name, description, admin_id) values (53, 'Bigtax', 'Osteomyelitis NOS-shlder', 63);
insert into communities (id, name, description, admin_id) values (54, 'Y-find', 'Mal neo postcricoid', 6);
insert into communities (id, name, description, admin_id) values (55, 'Zamit', 'Deep 3rd deg burn scalp', 83);
insert into communities (id, name, description, admin_id) values (56, 'Zamit', 'Hemorrhagic cond NEC', 69);
insert into communities (id, name, description, admin_id) values (57, 'It', 'Secondary parkinsonism', 66);
insert into communities (id, name, description, admin_id) values (58, 'Zontrax', 'Atrophic nonflaccid tymp', 99);
insert into communities (id, name, description, admin_id) values (59, 'Lotlux', 'Enophthalmos NOS', 61);
insert into communities (id, name, description, admin_id) values (60, 'Konklab', 'Centipede bite', 59);
insert into communities (id, name, description, admin_id) values (61, 'Lotlux', 'Pseudomonas enteritis', 56);
insert into communities (id, name, description, admin_id) values (62, 'Fixflex', 'Extradur hem-brief coma', 16);
insert into communities (id, name, description, admin_id) values (63, 'Transcof', 'Brachial plexus injury', 68);
insert into communities (id, name, description, admin_id) values (64, 'Gembucket', 'Viral dis contact NEC', 77);
insert into communities (id, name, description, admin_id) values (65, 'Greenlam', 'Anaplastic lymph axilla', 88);
insert into communities (id, name, description, admin_id) values (66, 'Regrant', 'Carbuncle of hand', 4);
insert into communities (id, name, description, admin_id) values (67, 'Bamity', 'Burn w eyeball destruct', 53);
insert into communities (id, name, description, admin_id) values (68, 'Y-Solowarm', 'Prim pulm hypertension', 23);
insert into communities (id, name, description, admin_id) values (69, 'Holdlamis', 'Myotonia congenita', 49);
insert into communities (id, name, description, admin_id) values (70, 'Regrant', 'Screen-sickle cell dis', 43);
insert into communities (id, name, description, admin_id) values (71, 'Rank', 'Vaginitis NOS', 38);
insert into communities (id, name, description, admin_id) values (72, 'Vagram', 'Ab ftl hrt rt/rh dur lab', 13);
insert into communities (id, name, description, admin_id) values (73, 'Pannier', 'Act leuk uns cl w rmson', 3);
insert into communities (id, name, description, admin_id) values (74, 'Y-find', 'Abdmnal rgdt lft up quad', 28);
insert into communities (id, name, description, admin_id) values (75, 'Sub-Ex', 'Polyostotic fibros dyspl', 39);
insert into communities (id, name, description, admin_id) values (76, 'Stim', 'Cyst of bone NOS', 16);
insert into communities (id, name, description, admin_id) values (77, 'Otcom', 'Dosag fail-shock therapy', 9);
insert into communities (id, name, description, admin_id) values (78, 'Cardguard', 'Hyposmolality', 79);
insert into communities (id, name, description, admin_id) values (79, 'Asoka', 'Abn dark adaptat curve', 100);
insert into communities (id, name, description, admin_id) values (80, 'Hatity', 'Perfor root canal space', 7);
insert into communities (id, name, description, admin_id) values (81, 'Stim', 'TB lung infiltr-exm unkn', 88);
insert into communities (id, name, description, admin_id) values (82, 'Domainer', 'Aft surg skin/subcu NEC', 97);
insert into communities (id, name, description, admin_id) values (83, 'Bytecard', 'Excessive attrition-pulp', 99);
insert into communities (id, name, description, admin_id) values (84, 'Zontrax', 'Rh incompat reaction NEC', 98);
insert into communities (id, name, description, admin_id) values (85, 'Sonair', 'Sclerosing mesenteritis', 1);
insert into communities (id, name, description, admin_id) values (86, 'Toughjoyfax', 'RR acc NEC-person NEC', 82);
insert into communities (id, name, description, admin_id) values (87, 'Namfix', 'Adv eff irrit cathartic', 93);
insert into communities (id, name, description, admin_id) values (88, 'Subin', 'Mental dis preg-unspec', 88);
insert into communities (id, name, description, admin_id) values (89, 'Greenlam', 'Allerg arthritis-hand', 22);
insert into communities (id, name, description, admin_id) values (90, 'Alpha', 'Pois-coronary vasodilat', 5);
insert into communities (id, name, description, admin_id) values (91, 'Redhold', 'Lipoma skin face', 8);
insert into communities (id, name, description, admin_id) values (92, 'Holdlamis', 'Obsessive-compulsive dis', 86);
insert into communities (id, name, description, admin_id) values (93, 'Fix San', 'Hx of colonic malignancy', 23);
insert into communities (id, name, description, admin_id) values (94, 'Latlux', 'Other dsrders esophagus', 30);
insert into communities (id, name, description, admin_id) values (95, 'Wrapsafe', 'Ac kidny fail w del-unsp', 30);
insert into communities (id, name, description, admin_id) values (96, 'Mat Lam Tam', 'Adv eff diuretics NEC', 5);
insert into communities (id, name, description, admin_id) values (97, 'Opela', 'Cong heart anomaly NEC', 39);
insert into communities (id, name, description, admin_id) values (98, 'It', 'Injury of chest wall NEC', 25);
insert into communities (id, name, description, admin_id) values (99, 'Gembucket', 'Psoriatic arthropathy', 30);
insert into communities (id, name, description, admin_id) values (100, 'It', 'Fet/plac prob NEC-deliv', 44);
